[package]
name = "xal"
version = "0.1.0"
authors = ["Bilal Ahsan <three6tdegree@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["dylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.79"
fltk = "^0.9"